spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  data:
    redis:
      host: localhost
      port: 6379
      password: ''
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0


