server:
  port: 3032
spring:
  application:
    name: orders
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5435/orders
    username: steelzen
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka